import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedSlashscreenpicsWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedBACKWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedPLUCKITFRESHWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedNavigationWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedForwardbuttonWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedPickyourfruitsandvegetablesfromourmenuofover150itemsWid.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedSKIPWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedslashscreenwidget/generated/GeneratedEllipse4Widget.dart';

/* Frame slash screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSlashscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 210, 214, 215),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 625.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 288.0,
                child: GeneratedSlashscreenpicsWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 61.0,
                child: GeneratedPLUCKITFRESHWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 44.0,
                child:
                    GeneratedPickyourfruitsandvegetablesfromourmenuofover150itemsWid(),
              ),
              Positioned(
                left: 0.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 187.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 70.0,
                child: GeneratedForwardbuttonWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 22.0,
                child: GeneratedBACKWidget(),
              ),
              Positioned(
                left: 312.0,
                top: 766.0,
                right: null,
                bottom: null,
                width: 39.0,
                height: 22.0,
                child: GeneratedSKIPWidget(),
              ),
              Positioned(
                left: 164.0,
                top: 775.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 775.0,
                right: null,
                bottom: null,
                width: 5.0,
                height: 5.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 180.0,
                top: 777.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 1.0,
                child: GeneratedRectangle4Widget(),
              )
            ]),
      ),
    ));
  }
}
