import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedPhonecallWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedLocationhomeWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedID46HD7KWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedButtonpaletteWidget4.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedIntransitWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedBrianBallWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedTrackingWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedClockWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedUndraw_current_location_rypt1Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedIVXoVHXqVCYWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedArrow2Widget3.dart';
import 'package:flutterapp/fruitsappapp/generatedtrackingwidget/generated/GeneratedNavigationWidget6.dart';

/* Frame Tracking
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTrackingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 210, 214, 215),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -29.0,
                right: null,
                bottom: null,
                width: 375.1180419921875,
                height: 255.0377960205078,
                child: GeneratedButtonpaletteWidget4(),
              ),
              Positioned(
                left: 24.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget6(),
              ),
              Positioned(
                left: 201.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 0.0,
                child: GeneratedArrow2Widget3(),
              ),
              Positioned(
                left: 24.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 43.0,
                child: GeneratedTrackingWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 85.0,
                child: GeneratedLocationhomeWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 335.0,
                child: GeneratedUndraw_current_location_rypt1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 95.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 578.0,
                right: null,
                bottom: null,
                width: 63.177494049072266,
                height: 67.0,
                child: GeneratedIVXoVHXqVCYWidget(),
              ),
              Positioned(
                left: 119.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 26.0,
                child: GeneratedBrianBallWidget(),
              ),
              Positioned(
                left: 121.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 17.0,
                child: GeneratedID46HD7KWidget(),
              ),
              Positioned(
                left: 121.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 17.0,
                child: GeneratedIntransitWidget(),
              ),
              Positioned(
                left: 284.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 46.0,
                child: GeneratedRectangle22Widget(),
              ),
              Positioned(
                left: 291.2254638671875,
                top: 603.0933837890625,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPhonecallWidget(),
              ),
              Positioned(
                left: 211.05078125,
                top: 707.701171875,
                right: null,
                bottom: null,
                width: 18.799999237060547,
                height: 18.799999237060547,
                child: GeneratedClockWidget(),
              )
            ]),
      ),
    ));
  }
}
