import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated\$800Widget3.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedMinusiconWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedPlusiconWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated1Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated\$640Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedZ9vkyDW9brwWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedOrangeWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated2Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated\$1176Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedNavigationWidget4.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedZa9HGBK5ALAWidget2.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedTotallistWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedButtonpaletteWidget2.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated\$1176Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedNibgG33H0F8Widget2.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedArrow2Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated\$1600Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedBasketWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedPlusiconWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedPlusiconWidget2.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedTangerineWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedShoppingbagWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated4Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedEnterPromoCodeWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedCucumberWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/Generated\$2560Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedAPPLYWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedMinusiconWidget2.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedMinusiconWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedbasketwidget/generated/GeneratedBUTTONWidget1.dart';

/* Frame Basket
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBasketWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 210, 214, 215),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -29.0,
                right: null,
                bottom: null,
                width: 375.1180419921875,
                height: 255.0377960205078,
                child: GeneratedButtonpaletteWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget4(),
              ),
              Positioned(
                left: 201.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 0.0,
                child: GeneratedArrow2Widget1(),
              ),
              Positioned(
                left: 92.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 40.0,
                child: GeneratedBUTTONWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 81.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 50.0,
                child: GeneratedBasketWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 72.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 72.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 72.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 50.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 250.0,
                top: 492.3653564453125,
                right: null,
                bottom: null,
                width: 92.0,
                height: 36.269229888916016,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 237.0,
                right: null,
                bottom: null,
                width: 58.79244613647461,
                height: 61.0,
                child: GeneratedNibgG33H0F8Widget2(),
              ),
              Positioned(
                left: 43.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 59.0,
                child: GeneratedZa9HGBK5ALAWidget2(),
              ),
              Positioned(
                left: 43.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 61.212642669677734,
                child: GeneratedZ9vkyDW9brwWidget1(),
              ),
              Positioned(
                left: 112.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 29.0,
                child: GeneratedOrangeWidget2(),
              ),
              Positioned(
                left: 112.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 29.0,
                child: GeneratedCucumberWidget(),
              ),
              Positioned(
                left: 112.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 29.0,
                child: GeneratedTangerineWidget1(),
              ),
              Positioned(
                left: 112.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 23.0,
                child: Generated$800Widget3(),
              ),
              Positioned(
                left: 112.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 23.0,
                child: Generated$1176Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 23.0,
                child: Generated$640Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.032;

                  final double height =
                      constraints.maxHeight * 0.014778325123152709;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.3078817733990148,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPlusiconWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.032;

                  final double height =
                      constraints.maxHeight * 0.014778325123152709;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.4088669950738916,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPlusiconWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.032;

                  final double height =
                      constraints.maxHeight * 0.014778325123152709;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.816,
                        y: constraints.maxHeight * 0.5110837438423645,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPlusiconWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.032;

                  final double height =
                      constraints.maxHeight * 0.014778325123152709;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7208888346354166,
                        y: constraints.maxHeight * 0.3082922573747306,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMinusiconWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.032;

                  final double height =
                      constraints.maxHeight * 0.014778325123152709;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7208888346354166,
                        y: constraints.maxHeight * 0.40927747904960743,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMinusiconWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.032;

                  final double height =
                      constraints.maxHeight * 0.014778325123152709;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.7208888346354166,
                        y: constraints.maxHeight * 0.5114942278180804,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMinusiconWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 290.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 15.0,
                height: 29.0,
                child: Generated2Widget1(),
              ),
              Positioned(
                left: 292.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 12.0,
                height: 29.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 289.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 29.0,
                child: Generated4Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 23.0,
                child: Generated$1600Widget(),
              ),
              Positioned(
                left: 283.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 23.0,
                child: Generated$1176Widget1(),
              ),
              Positioned(
                left: 277.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 23.0,
                child: Generated$2560Widget(),
              ),
              Positioned(
                left: 266.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 32.0,
                child: GeneratedAPPLYWidget(),
              ),
              Positioned(
                left: 42.900970458984375,
                top: 497.6705322265625,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShoppingbagWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 27.0,
                child: GeneratedEnterPromoCodeWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 598.0,
                right: null,
                bottom: null,
                width: 325.944580078125,
                height: 107.0,
                child: GeneratedTotallistWidget(),
              )
            ]),
      ),
    ));
  }
}
