import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedCitrusfruitscardWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedVegetablescardWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedNibgG33H0F8Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedTangerinepriceWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedLetspluckWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedSeeallWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedBerriescardWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedOrangepriceWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedDiscountadWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedButtonpaletteWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedNavigationWidget2.dart';
import 'package:flutterapp/fruitsappapp/generatedmenuscreenwidget/generated/GeneratedBASENAVIGATIONWidget.dart';

/* Frame MENU screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMENUscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 210, 214, 215),
                ),
              ),
              Positioned(
                left: -0.0007817992009222507,
                top: -27.9986572265625,
                right: null,
                bottom: null,
                width: 375.1180419921875,
                height: 259.0354309082031,
                child: GeneratedButtonpaletteWidget(),
              ),
              Positioned(
                left: 564.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 91.40034484863281,
                height: 83.0,
                child: GeneratedNibgG33H0F8Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 88.0,
                child: GeneratedDiscountadWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 367.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 47.0,
                child: GeneratedLetspluckWidget(),
              ),
              Positioned(
                left: 306.0,
                top: 385.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 23.0,
                child: GeneratedSeeallWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedCitrusfruitscardWidget(),
              ),
              Positioned(
                left: 155.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedBerriescardWidget(),
              ),
              Positioned(
                left: 283.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 50.0,
                child: GeneratedVegetablescardWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 195.0,
                child: GeneratedOrangepriceWidget(),
              ),
              Positioned(
                left: 213.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 195.0,
                child: GeneratedTangerinepriceWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 760.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 40.0,
                child: GeneratedBASENAVIGATIONWidget(),
              )
            ]),
      ),
    ));
  }
}
