import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generatedlaunchscreenwidget/generated/GeneratedLogoWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedlaunchscreenwidget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedlaunchscreenwidget/generated/GeneratedNavigationWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedlaunchscreenwidget/generated/GeneratedSlashscreenpicsWidget.dart';

/* Frame launch screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLaunchscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 238, 10, 34),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 625.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget(),
              ),
              Positioned(
                left: 537.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 316.0,
                child: GeneratedSlashscreenpicsWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 219.0,
                height: 120.0,
                child: GeneratedLogoWidget(),
              )
            ]),
      ),
    ));
  }
}
