import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedPayPalWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedTotallistWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedCreditCardWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedLocationworkplaceWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedEllipse8Widget1.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedBUTTONWidget2.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedArrow2Widget2.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedPngwing1Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedLocationhomeWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedNavigationWidget5.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedButtonpaletteWidget3.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedCheckoutWidget1.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedMoreverticalWidget.dart';
import 'package:flutterapp/fruitsappapp/generatedcheckoutwidget/generated/GeneratedPngaaa1Widget.dart';

/* Frame checkout
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 210, 214, 215),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -29.0,
                right: null,
                bottom: null,
                width: 375.1180419921875,
                height: 255.0377960205078,
                child: GeneratedButtonpaletteWidget3(),
              ),
              Positioned(
                left: 24.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget5(),
              ),
              Positioned(
                left: 201.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 0.0,
                child: GeneratedArrow2Widget2(),
              ),
              Positioned(
                left: 92.0,
                top: 735.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 40.0,
                child: GeneratedBUTTONWidget2(),
              ),
              Positioned(
                left: 24.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 43.0,
                child: GeneratedCheckoutWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 27.0,
                child: GeneratedTotallistWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 85.0,
                child: GeneratedLocationworkplaceWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 64.0,
                child: GeneratedRectangle19Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 568.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 64.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 122.0,
                top: 512.8235473632812,
                right: null,
                bottom: null,
                width: 133.0,
                height: 33.447059631347656,
                child: GeneratedCreditCardWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 36.0,
                child: GeneratedPayPalWidget(),
              ),
              Positioned(
                left: 294.0,
                top: 519.7294921875,
                right: null,
                bottom: null,
                width: 17.0,
                height: 16.200000762939453,
                child: GeneratedEllipse8Widget1(),
              ),
              Positioned(
                left: 294.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 16.19999885559082,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 295.888916015625,
                top: 521.529541015625,
                right: null,
                bottom: null,
                width: 13.222222328186035,
                height: 12.59999942779541,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 306.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedMoreverticalWidget(),
              ),
              Positioned(
                left: 25.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 268.0,
                child: GeneratedLocationhomeWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 511.0,
                right: null,
                bottom: null,
                width: 69.36774444580078,
                height: 42.0,
                child: GeneratedPngwing1Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 588.1500244140625,
                right: null,
                bottom: null,
                width: 69.0,
                height: 27.600000381469727,
                child: GeneratedPngaaa1Widget(),
              )
            ]),
      ),
    ));
  }
}
