import 'package:flutter/material.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedBUTTONWidget.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedOrangefleshis87water12carbohydrates1proteinandcontainsn.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/Generated\$800Widget2.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedVectorWidget22.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedArrow2Widget.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedNavigationWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedButtonpaletteWidget1.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedPCjw_ygKCv0Widget.dart';
import 'package:flutterapp/fruitsappapp/generateditemscreenwidget/generated/GeneratedOrangeWidget1.dart';

/* Frame item screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedItemscreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 210, 214, 215),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -29.0,
                right: null,
                bottom: null,
                width: 375.1180419921875,
                height: 255.0377960205078,
                child: GeneratedButtonpaletteWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 21.0,
                child: GeneratedNavigationWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09170967610677083;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 34.39112854003906;

                  double percentHeight = 0.03694107497266948;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      29.996152877807617;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.45066666666666666,
                        translateY: constraints.maxHeight * 0.18472906403940886,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget22())
                  ]);
                }),
              ),
              Positioned(
                left: 345.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 265.0,
                height: 319.0,
                child: GeneratedPCjw_ygKCv0Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 92.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 0.0,
                child: GeneratedArrow2Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 50.0,
                child: GeneratedOrangeWidget1(),
              ),
              Positioned(
                left: 267.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 50.0,
                child: Generated$800Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 77.0,
                child:
                    GeneratedOrangefleshis87water12carbohydrates1proteinandcontainsn(),
              ),
              Positioned(
                left: 92.0,
                top: 678.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 40.0,
                child: GeneratedBUTTONWidget(),
              )
            ]),
      ),
    ));
  }
}
